Add LevelTag
sayas01/atlas pull request #3
Opened 2018-12-06 00:48 UTC by sayas01

### Description:

This PR adds [LevelTag](https://wiki.openstreetmap.org/wiki/Key:level) to Atlas. The range of the tag value has been set based on tag values with count greater than 0.5%. 

### Potential Impact:

No potential impact except that the new tag can be used.

### Unit Test Approach:

NA

### Test Results:

NA

------

In doubt: [Contributing Guidelines](CONTRIBUTING.md)

2018-12-06 19:27 UTC, Bentleysb requested changes

2018-12-06 19:27 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/tags/LevelTag.java
> +@Tag(value = Tag.Validation.LONG, range = @Tag.Range(min = -3, max = 5), taginfo = "http://taginfo.openstreetmap.org/keys/level#values", osm = "http://wiki.openstreetmap.org/wiki/Level")
This tag is used for indoor mapping. So I would think the range should reflect the levels of buildings in the world, not just what is currently tagged in OSM. I did a little research and found that the highest number of positive floors in the world is currently 163 (see https://en.wikipedia.org/wiki/List_of_buildings_with_100_floors_or_more). I could not find a good number for levels below ground.

2018-12-06 19:27 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/tags/LevelTag.java
> +    static Optional<Long> getTaggedValue(final Taggable taggable)
It would be good to have a `getTaggedOrImpliedValue` as well, method like layer tag has.

2018-12-06 22:15 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/tags/LevelTag.java
> +@Tag(value = Tag.Validation.LONG, range = @Tag.Range(min = -3, max = 5), taginfo = "http://taginfo.openstreetmap.org/keys/level#values", osm = "http://wiki.openstreetmap.org/wiki/Level")
No range works too.

2018-12-06 22:15 UTC, Bentleysb approved these changes
LGTM

2018-12-06 22:17 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/tags/LevelTag.java
> +@Tag(value = Tag.Validation.LONG, range = @Tag.Range(min = -3, max = 5), taginfo = "http://taginfo.openstreetmap.org/keys/level#values", osm = "http://wiki.openstreetmap.org/wiki/Level")
Yes, I believe it would be best to leave the range out.

2018-12-07 17:37 UTC, danielduhh approved these changes
Looks good

2018-12-07 17:38 UTC, closed without merging