Complex Entity for AOI Relations
sayas01/atlas pull request #4
Opened 2018-12-27 15:18 UTC by sayas01

### Description:

This PR adds new feature to Atlas to include Complex Entity support for Areas Of Interest (AOI). This PR addresses the OSM issue [#163](https://github.com/osmlab/atlas/issues/163. Two new classes added are:
1. ComplexAOIRelation : ComplexEntity implementation of Multipolygon AOI relations. 
2. ComplexAOIRelationFinder : For the given Atlas, builds complex entities for all the AOIs that are represented by Multipolygon relations.
Currently, the implementation uses a small subset of 600+ key-value pairs of AOI tags (filtered from https://wiki.openstreetmap.org/wiki/Map_Features). The source of the subset AOI tags is the [OverlappingAOIPolygonCheck](https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java). 

### Potential Impact:

The new feature could be made use of in getting geometries of AOI.

### Unit Test Approach:

Added test cases for the ComplexAOIRelationFinder class.

### Test Results:

All tests passed.

------

In doubt: [Contributing Guidelines](CONTRIBUTING.md)

2018-12-27 17:39 UTC, nachtm requested changes
🔥 This is awesome! A couple style comments, but this is a nicely-done ComplexEntity 🙂

2018-12-27 17:39 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAOIRelation.java
> +        return !(source instanceof Relation && AOI_TAG_FILTER.test(source)) ? Optional.empty()
Could we switch these around? So
```
(source instanceof Relation && AOI_TAG_FILTER.test(source)) ? Optional.of(...) : Optional.empty();
```

2018-12-27 17:39 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAOIRelation.java
> +                && (AOI_TAG_FILTER.test(source) || aoiFilter.test(source))) ? Optional.empty()
See above. Also, if there's a `TaggableFilter` that matches nothing, we could probably have the last function call this one 😄

2018-12-27 17:39 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAOIRelation.java
> +            setInvalidReason("Unable to create complex islands", exception);
nit: complex AOIs?

2018-12-27 17:51 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/ComplexAOIRelation.java
> +    private static final TaggableFilter AOI_TAG_FILTER = TaggableFilter.forDefinition(
I would consider turning this into a json resource, as I can see the list of aois growing substantially.

2018-12-27 18:33 UTC, nachtm approved these changes
🎉 ❗️

2018-12-28 18:16 UTC, Bentleysb approved these changes
LGTM

2019-01-09 19:31 UTC, danielduhh commented on src/main/resources/org/openstreetmap/atlas/geography/atlas/items/complex/aoi/aoi-tag-filter.json
> +    "aerialway->STATION",
Nice! Lets make sure to mention that the OSM wiki was the source for this

2019-01-09 19:54 UTC, danielduhh approved these changes
Looks good! Thanks @sayas01

2019-01-10 00:28 UTC, closed without merging